
on:
  pull_request:
    branches: [ "main" ]
    types: [ opened ]
    
jobs:

  do_on_create:
    runs-on: ubuntu-latest
    steps:
      - name: on_create
        run: echo "On Create"
        
      - name: create_label
        env:
          URL: ${{ github.event.pull_request.labels.url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl \
            -X POST \
            $URL \
            -H "Content-Type: application/json" \
            -H "Authorization: token $GITHUB_TOKEN" \
            --data '{ "body": "Dev Approved" }'
