on:
  workflow_dispatch:
    
jobs:

  do_on_create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          path: gitcheckout
      
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: 'maven'
      
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      
      - name: Install Dependencies
        working-directory: gitcheckout
        run: mvn --batch-mode -Dmaven.repo.local=./cache/.m2/repository -s /home/runner/.m2/settings.xml dependency:copy-dependencies
        
      - name: Build Maven cache
        id: check-mvn-cache
        uses: actions/cache@v3.2.3
        with:
          path: ./cache/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Build with Maven
        working-directory: gitcheckout
        run: mvn --batch-mode -Dmaven.repo.local=./cache/.m2/repository -s /home/runner/.m2/settings.xml -B test
          
#       - name: on_create
#         run: echo "On Create"
        
#       - name: create_label
#         env:
#           URL: ${{ github.event.pull_request.url }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         run: |
#           curl --location --request POST 'https://api.github.com/repos/BerryGelan/github-actions/issues/${{ github.event.pull_request.number }}/labels' \
#                --header "Accept: application/vnd.github.v3+json" \
#                --header "Authorization: token $GITHUB_TOKEN" \
#                --header "Content-Type: application/json" \
#                --data-raw '{
#                    "labels": ["enhancement"]
#                }'
