name: iftp-workflow

on:
  workflow_call:
    
jobs:
  do_on_create:
    uses: ./.github/workflows/dev.yml
  do_on_label:
    uses: ./.github/workflows/stage.yml
  do_on_merge:
    uses: ./.github/workflows/prod.yml
