name: IFTP-DEPLOY

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]
    
jobs:
  metadata:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        maven: [ '3.8.6' ]

    steps:
      - name: Pull Request
        run: |
          echo "'${{ github.event.pull_request.title }} #${{ github.event.number }}' (${{ github.event.pull_request.state }})"
          echo "${{ github.event.pull_request.merged_by.login }} merged into '${{ github.event.pull_request.base.ref }}' from '${{ github.event.pull_request.head.ref }}'"
          echo "${{ github.event.pull_request._links.html.href }}"
          echo "Mimer team approvals: '${{ github.event.pull_request_review.author.login }}'"
          echo "Business approvals: 'business_man'"
          
      - name: Maven
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: 11
          maven-version: ${{ matrix.maven }}
      - run: mvn -V
          

