name: IFTP-DEPLOY

on:
  pull_request:
    branches: [ "main" ]
    # when PR is merged
    # alternative is to use:
    # jobs:
    #   build:
    #     if: github.event.pull_request.merged == 'true'
    types: [ closed ]
    
jobs:
  build:
#     if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Pull Request metadata
        run: |
          echo "Triggered by"
          echo "(${{ github.event.pull_request.state }})'${{ github.event.pull_request.title }} #${{ github.event.number }}'"
          echo "${{ github.event.pull_request.user.login }} merged into '${{ github.event.pull_request.base.ref }}' from '${{ github.event.pull_request.head.ref }}'"
          echo "Developer approval from  ${{ github.event.pull_request.requested_reviewers.login }}"
          echo "Business approval from   business_man"
          echo "${{ github.event.pull_request._links.html.href }}"
          
          
      - name: Show username
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
        run: echo "User is $USER_NAME"
