name: iftp-workflow

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened ]
    
jobs:
  do_on_create:
    uses: ./.github/workflows/dev.yml
  do_on_merge:
    uses: ./.github/workflows/prod.yml
