name: IFTP-DEPLOY

on:
  pull_request:
    branches: [ "main" ]
    types: [ closed ]
    
jobs:

  install_tools:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '11' ]
        maven: [ '3.8.6' ]
    steps:
      - name: Maven Install
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: ${{ matrix.java }}
          maven-version: ${{ matrix.maven }}
          
      - name: Maven Version
        run: mvn -V validate -Drequire.java=${{ matrix.java }} -Drequire.maven=${{ matrix.maven }}
    
  metadata:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Request
        run: |
          echo "'${{ github.event.pull_request.title }} #${{ github.event.number }}' (${{ github.event.pull_request.state }})"
          echo "${{ github.event.pull_request.merged_by.login }} merged into '${{ github.event.pull_request.base.ref }}' from '${{ github.event.pull_request.head.ref }}'"
          echo "${{ github.event.pull_request._links.html.href }}"
          echo "Mimer team approvals: '${{ github.event.pull_request_review.author.login }}'"
          echo "Business approvals: 'business_man'"
          
