name: dev-workflow

on:
  pull_request_review:
    types: [submitted]
    
jobs:
        
  oc_pr_approve:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: on_approve
        run: echo "On Approve"
