name: prod-workflow

on:
  pull_request_target:
    types:
      - closed
    
jobs:
        
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: on_approve
        run: echo "On Merge"
