name: reusable-example

on:
  workflow_dispatch:
    inputs:
      release-version:
        type: string
        description: Enter release version
        required: true
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - dev
          - stg
          - prod
          
jobs:
  create_file:
    if: "${{ github.event.inputs.environment == 'dev' }}"
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          pwd
          ls
          mkdir ./example/
          touch ./example/${{ github.event.inputs.environment }}_${{ github.event.inputs.release-version }}.log
          echo "Dev version ${{ github.event.inputs.release-version }}" > ./example/dev_file_example.log
          ls
    
      - name: Upload file
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.inputs.environment }}_${{ github.event.inputs.release-version }}
          path: ./example/${{ github.event.inputs.environment }}_${{ github.event.inputs.release-version }}.log

  output:
    if: "${{ github.event.inputs.environment == 'stg' }}"
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: "Download artifact"
#        run: |
#          gh api -H "Accept: application/vnd.github+json" /repos/BerryGelan/github-actions/actions/runs/3823541791/artifacts
        run: |
          OTHER_REPO="BerryGelan/github-actions"
          WF_NAME="reusable-example"
          ARTIFACT_NAME="dev_${{ github.event.inputs.release-version }}"
          echo $(gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[*].databaseId)
#          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
#          echo $RUN_ID
#          gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - run: |
          ls
          cd ./example
          cat dev_${{ github.event.inputs.release-version }}.log
