name: stage

on:
  workflow_dispatch:
    inputs:
      release-version:
        type: string
        description: Enter release version
        required: true
      pr-number:
        type: string
        description: Development Approved Run Number
        required: true
          
jobs:
  output:
    environment: ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: "Download artifact"
#        run: |
#          gh api -H "Accept: application/vnd.github+json" /repos/BerryGelan/github-actions/actions/runs/3823541791/artifacts
        run: |
          OTHER_REPO="BerryGelan/github-actions"
          WF_NAME="development"
          ARTIFACT_NAME="dev_${{ github.event.inputs.release-version }}"
          echo $(gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json status,databaseId,number --jq '.[] | select(.status == "completed") | select(.number == ${{ github.event.inputs.pr-number }})' --jq .[].databaseId)
#          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[0].databaseId`
#          echo $RUN_ID
#          gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - run: |
          ls
          cd ./example
          cat dev_${{ github.event.inputs.release-version }}.log
